"""add ph col

Revision ID: fb866ad32d99
Revises: 79a2a7ad70ef
Create Date: 2023-12-21 12:55:49.992685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb866ad32d99'
down_revision: Union[str, None] = '79a2a7ad70ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ph_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ph_number')
    # ### end Alembic commands ###
